const COMPONENT_TYPE = {
    CPU: "CPU",
    RAM: "RAM",
    MONITOR: "MONITOR",
    MOTHERBOARD: "MOTHERBOARD",
    STORAGE: "STORAGE",
    POWER_SUPPLY_UNIT: "POWER_SUPPLY_UNIT",
};

export default COMPONENT_TYPE;
